-- OM 2021.02.17
-- FICHIER MYSQL POUR FAIRE FONCTIONNER LES EXEMPLES
-- DE REQUETES MYSQL
-- Database: MACCAUD_OLIVIER_INFO1X_FILMS_164_2023

-- Destruction de la BD si elle existe.
-- Pour être certain d'avoir la dernière version des données

DROP DATABASE IF EXISTS MACCAUD_OLIVIER_INFO1X_FILMS_164_2023;

-- Création d'un nouvelle base de donnée

CREATE DATABASE IF NOT EXISTS MACCAUD_OLIVIER_INFO1X_FILMS_164_2023;

-- Utilisation de cette base de donnée

USE MACCAUD_OLIVIER_INFO1X_FILMS_164_2023;
-- --------------------------------------------------------
-- mettre ma base de données ci-dessous :